version: '3.8'

services:
  gin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # mapping container's port 3000 to my 3000
    volumes:
      - ./config.json:/app/config.json:ro  # copy config as readonly
    depends_on:
      - postgres
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: "john_wick"
      POSTGRES_USER: "john"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
